#!/usr/bin/env zsh
# choose the server to login

# Initialization
# ssh-agent
[ "$(ssh-add -l 2>/dev/null)" ] || ssh-add ~/.ssh/id_rsa

# Which server to choose
# chosen=$(grep -v "#" $homeSys/xshare/server.info | awk '{print $1}'| dmenu -g 1 -i -p 'choose the ssh server' -l 20 -fn Arial)
# [ "$chosen" != "" ] || exit
# info=$(grep "$chosen" $homeSys/xshare/server.info)

# user@server_name (e.g., mr-superonion@soupy_onion.com)
s=
# port name (e.g, 9582)
p=

# kill existing identical connections first
pids=$(lsof -i :"$port1" | awk '/IPv4/ && /LISTEN/ {print $2}')
if [ pids ]; then
    kill $pids
fi

# Connect to remote Jupyter server
## Download the file file storing the port client name on remote server
port1="$p"
client=$(ssh "$s" cat \$HOME/.cache/jupyterlab.info | awk '{print $1}')
port3=$(ssh "$s" cat \$HOME/.cache/jupyterlab.info | awk '{print $2}')

cmd="ssh -f -N -L "$port1":"$client":$port3 $s"
echo "$cmd"
eval "$cmd"
url="http://localhost:$port1"
echo "URL that will open in your browser:"
echo "$url"

# If you do not have firefox, just comment this out and open the url in your
# browser
firefox "$url"
