#!/usr/bin/env bash

#
# post the job into queue
#
datetime="`date +%d%H%M%S`"
JobName="sonion-"$datetime
foo="#!/usr/bin/env bash
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 20
#SBATCH --time 48:00:00
#SBATCH --job-name $JobName
#SBATCH --output sonion-out-$datetime
#SBATCH --error sonion-err-$datetime
#SBATCH --mem=80G
$(export)
$(export -f)
cd $PWD
$@
"

cd $PWD &&
echo "${foo@E}" | sbatch
